stages:
  train:
    cmd: python3 src/train_model.py data/ outputs/models/
    deps:
    - src/train_model.py
    - src/common/
    - data/
    outs:
    - outputs/models/
  build_inference:
    cmd: docker build -t nidhogg-inference -f docker/inference.Dockerfile .
    deps:
    - docker/inference.Dockerfile
    - src/inference_api.py
    - src/common/
    - outputs/models/
  build_frontend:
    cmd: docker build -t nidhogg-frontend -f docker/frontend.Dockerfile .
    deps:
    - docker/frontend.Dockerfile
    - src/frontend.py
    - src/frontend/
