stages:
  train:
    cmd: poetry run python3 src/train_model.py data/ outputs/nltk_corpora/ outputs/models/
    deps:
    - src/train_model.py
    - src/common/
    - data/
    outs:
    - outputs/nltk_corpora/
    - outputs/models/
  build_inference:
    cmd: docker build -t nidhogg-inference -f docker/inference.Dockerfile .
    deps:
    - docker/inference.Dockerfile
    - poetry.lock
    - src/inference.py
    - src/common/
    - outputs/models/vectorizer.pkl
    - outputs/models/tfidf_model.pkl
  build_alertmetrics:
    cmd: docker build -t alertmetrics -f docker/alertmetrics.Dockerfile .
    deps:
    - docker/alertmetrics.Dockerfile
    - src/alertmetrics/
    - poetry.lock
  build_frontend:
    cmd: docker build -t nidhogg-frontend -f docker/frontend.Dockerfile .
    deps:
    - docker/frontend.Dockerfile
    - poetry.lock
    - src/frontend/
