name: Train model, build containers and create a new version tag

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

env:
#  is_push_to_main: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
  is_push_to_main: ${{ github.ref == 'refs/heads/main' }} # TEMPORARY, this should not appear in the git history. If it does, punch jurriaan.

jobs:
  dvc-repro:
    name: "Run complete DVC pipeline"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
#          TEMPORARY DISABLED
#      - name: Setup Python 3.8
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.8'
#          cache: pip
#      - name: Setup Python dependencies
#        run: pip install -r requirements.txt
#      - name: Setup DVC
#        uses: iterative/setup-dvc@v1
#      - name: Run DVC pipeline
#        run: |
#          dvc repro

      # On pushes to main, we bump the minor version and push a new v* tag
      - name: Bump version and push tag
        if: ${{ env.is_push_to_main }}
        id: bumpVersion
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Tag the created docker images
        if: ${{ env.is_push_to_main }}
        run: |
          docker image tag nidhogg-inference:latest ghcr.io/Fastjur/nidhogg/nidhogg-inference:latest
          docker image tag nidhogg-inference:latest ghcr.io/Fastjur/nidhogg/nidhogg-inference:${{ steps.bumpVersion.tag }}
          docker image tag nidhogg-frontend:latest ghcr.io/Fastjur/nidhogg/nidhogg-frontend:latest
          docker image tag nidhogg-frontend:latest ghcr.io/Fastjur/nidhogg/nidhogg-frontend:${{ steps.bumpVersion.tag }}

      - name: Log in to the Container registry
        if: ${{ env.is_push_to_main }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the docker images to the Container registry
        if: ${{ env.is_push_to_main }}
        run: |
          docker images push --all-tags ghcr.io/Fastjur/nidhogg/nidhogg-inference
          docker images push --all-tags ghcr.io/Fastjur/nidhogg/nidhogg-frontend

#      - name: Extract metadata (tags, labels) for Docker
#        if: ${{ env.is_push_to_main }}
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ matrix.image }}
#          tags: |
#            # Create a tag with the git commit hash
#            type=semver,pattern={{version}},value=${{ steps.bumpVersion.outputs.tag }}
#            # set latest tag for default branch
#            type=raw,value=latest,enable={{is_default_branch}}

#      - name: Build and push Docker image
#        if: ${{ env.is_push_to_main }}
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ${{ matrix.dockerfile }}
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
