name: "Terraform Google Cloud - Apply"

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: "Terraform init"
        id: init
        working-directory: "terraform"
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: "Terraform validate"
        id: validate
        working-directory: "terraform"
        run: terraform validate -no-color

      - name: "Terraform apply"
        id: apply
        # Double check to only run on pushtes to main (if someone alters the on push rules above)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: "terraform"
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}